name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Node.JS
        uses: actions/setup-node@v2
        with:
          check-latest: true
          cache: 'yarn'

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Restore rust cache
        uses: Swatinem/rust-cache@v1
        with:
          working-directory: browserslist-wasm
          target-dir: browserslist-wasm/target

      - name: Install Javascript dependencies
        run: yarn install --immutable

      - name: Run eslint linter
        run: yarn lint

      - name: Build wasm
        run: yarn wasm:release

      - name: Build website
        run: yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
